---
language: python
python: "2.7"

sudo: required
dist: trusty

before_script:
- cd tests
- sudo apt-get update
- sudo apt-get install -y ansible
- ansible --version

script:
- ansible-playbook test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
