---
language: python
python: "2.7"

sudo: requried
dist: trusty

addons:
  apt:
    packages:
    - python-pip

before_install: cd tests

install:
  - pip install ansible

  - ansible --version

script:
  - ansible-playbook test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
